baseURL = "https://jakobcarlsson.se"
languageCode = "en"
title = "Jakob Carlsson"
theme = "hugo-coder"

[[cascade]]
    [cascade.fields]
    type = "thought"
    [cascade.target]
    path = "/thoughts/**"
    kind = "page"


[pagination]
pagerSize = 6

[permalinks]
blog = "/blog/:slug/"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Jakob Carlsson"
description = "My personal place on the internet"
info = ["Senior Developer", "Solution Architect", "Public Speaker"]
dateFormat = "2006-01-02"
since = 2025
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
manifest = ""

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/jakobcarlsson-swe/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 2
url = "https://medium.com/@mylopeda"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/Mylopeda"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "blog/"

[[languages.en.menu.main]]
name = "Thoughts"
weight = 2
url = "thoughts/"

[[languages.en.menu.main]]
name = "Speaking"
weight = 3
url = "speaking/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"
